//
//  deck.swift
//  iOSProject
//
//  Created by Carli Weinberg on 4/25/18.
//  Copyright © 2018 Carli Weinberg. All rights reserved.
//

import Foundation
import UIKit

class deck {
    let OneGreenDiamondFull = #imageLiteral(resourceName: "OneGreenDiamondFull.png")
    let OneGreenDiamondEmpty = #imageLiteral(resourceName: "OneGreenDiamondEmpty.png")
    let OneGreenDiamondLined = #imageLiteral(resourceName: "OneGreenDiamondLined.png")
    let OneGreenOvalFull = #imageLiteral(resourceName: "OneGreenOvalFull.png")
    let OneGreenOvalEmpty = #imageLiteral(resourceName: "OneGreenOvalEmpty.png")
    let OneGreenOvalLined = #imageLiteral(resourceName: "OneGreenOvalLined.png")
    let OneGreenSFull = #imageLiteral(resourceName: "OneGreenSFull.png")
    let OneGreenSEmpty = #imageLiteral(resourceName: "OneGreenSEmpty.png")
    let OneGreenSLined = #imageLiteral(resourceName: "OneGreenSLined.png")
    let OneRedDiamondFull = #imageLiteral(resourceName: "OneRedDiamondFull.png")
    let OneRedDiamondEmpty = #imageLiteral(resourceName: "OneRedDiamondEmpty.png")
    let OneRedDiamondLined = #imageLiteral(resourceName: "OneRedDiamondLined.png")
    let OneRedOvalFull = #imageLiteral(resourceName: "OneRedOvalFull.png")
    let OneRedOvalEmpty = #imageLiteral(resourceName: "OneRedOvalEmpty.png")
    let OneRedOvalLined = #imageLiteral(resourceName: "OneRedOvalLined.png")
    let OneRedSFull = #imageLiteral(resourceName: "OneRedSFull.png")
    let OneRedSEmpty = #imageLiteral(resourceName: "OneRedSEmpty.png")
    let OneRedSLined = #imageLiteral(resourceName: "OneRedSLined.png")
    let OnePurpleDiamondFull = #imageLiteral(resourceName: "OnePurpleDiamondFull.png")
    let OnePurpleDiamondEmpty = #imageLiteral(resourceName: "OnePurpleDiamondEmpty.png")
    let OnePurpleDiamondLined = #imageLiteral(resourceName: "OnePurpleDiamondLined.png")
    let OnePurpleOvalFull = #imageLiteral(resourceName: "OnePurpleOvalFull.png")
    let OnePurpleOvalEmpty = #imageLiteral(resourceName: "OnePurpleOvalEmpty.png")
    let OnePurpleOvalLined = #imageLiteral(resourceName: "OnePurpleOvalLined.png")
    let OnePurpleSFull = #imageLiteral(resourceName: "OnePurpleSFull.png")
    let OnePurpleSEmpty = #imageLiteral(resourceName: "OnePurpleSEmpty.png")
    let OnePurpleSLined = #imageLiteral(resourceName: "OnePurpleSLined.png")
    let TwoGreenDiamondFull = #imageLiteral(resourceName: "TwoGreenDiamondFull.png")
    let TwoGreenDiamondEmpty = #imageLiteral(resourceName: "TwoGreenDiamondEmpty.png")
    let TwoGreenDiamondLined = #imageLiteral(resourceName: "TwoGreenDiamondLined.png")
    let TwoGreenOvalFull = #imageLiteral(resourceName: "TwoGreenOvalFull.png")
    let TwoGreenOvalEmpty = #imageLiteral(resourceName: "TwoGreenOvalEmpty.png")
    let TwoGreenOvalLined = #imageLiteral(resourceName: "TwoGreenOvalLined.png")
    let TwoGreenSFull = #imageLiteral(resourceName: "TwoGreenSFull.png")
    let TwoGreenSEmpty = #imageLiteral(resourceName: "TwoGreenSEmpty.png")
    let TwoGreenSLined = #imageLiteral(resourceName: "TwoGreenSLined.png")
    let TwoRedDiamondFull = #imageLiteral(resourceName: "TwoRedDiamondFull.png")
    let TwoRedDiamondEmpty = #imageLiteral(resourceName: "TwoRedDiamondEmpty.png")
    let TwoRedDiamondLined = #imageLiteral(resourceName: "TwoRedDiamondLined.png")
    let TwoRedOvalFull = #imageLiteral(resourceName: "TwoRedOvalFull.png")
    let TwoRedOvalEmpty = #imageLiteral(resourceName: "TwoRedOvalEmpty.png")
    let TwoRedOvalLined = #imageLiteral(resourceName: "TwoRedOvalLined.png")
    let TwoRedSFull = #imageLiteral(resourceName: "TwoRedSFull.png")
    let TwoRedSEmpty = #imageLiteral(resourceName: "TwoRedSEmpty.png")
    let TwoRedSLined = #imageLiteral(resourceName: "TwoRedSLined.png")
    let TwoPurpleDiamondFull = #imageLiteral(resourceName: "TwoPurpleDiamondFull.png")
    let TwoPurpleDiamondEmpty = #imageLiteral(resourceName: "TwoPurpleDiamondEmpty.png")
    let TwoPurpleDiamondLined = #imageLiteral(resourceName: "TwoPurpleDiamondLined.png")
    let TwoPurpleOvalFull = #imageLiteral(resourceName: "TwoPurpleOvalFull.png")
    let TwoPurpleOvalEmpty = #imageLiteral(resourceName: "TwoPurpleOvalEmpty.png")
    let TwoPurpleOvalLined = #imageLiteral(resourceName: "TwoPurpleOvalLined.png")
    let TwoPurpleSFull = #imageLiteral(resourceName: "TwoPurpleSFull.png")
    let TwoPurpleSEmpty = #imageLiteral(resourceName: "TwoPurpleSEmpty.png")
    let TwoPurpleSLined = #imageLiteral(resourceName: "TwoPurpleSLined.png")
    let ThreeGreenDiamondFull = #imageLiteral(resourceName: "ThreeGreenDiamondFull.png")
    let ThreeGreenDiamondEmpty = #imageLiteral(resourceName: "ThreeGreenDiamondEmpty.png")
    let ThreeGreenDiamondLined = #imageLiteral(resourceName: "ThreeGreenDiamondLined.png")
    let ThreeGreenOvalFull = #imageLiteral(resourceName: "ThreeGreenOvalFull.png")
    let ThreeGreenOvalEmpty = #imageLiteral(resourceName: "ThreeGreenOvalEmpty.png")
    let ThreeGreenOvalLined = #imageLiteral(resourceName: "ThreeGreenOvalLined.png")
    let ThreeGreenSFull = #imageLiteral(resourceName: "ThreeGreenSFull.png")
    let ThreeGreenSEmpty = #imageLiteral(resourceName: "ThreeGreenSEmpty.png")
    let ThreeGreenSLined = #imageLiteral(resourceName: "ThreeGreenSLined.png")
    let ThreeRedDiamondFull = #imageLiteral(resourceName: "ThreeRedDiamondFull.png")
    let ThreeRedDiamondEmpty = #imageLiteral(resourceName: "ThreeRedDiamondEmpty.png")
    let ThreeRedDiamondLined = #imageLiteral(resourceName: "ThreeRedDiamondLined.png")
    let ThreeRedOvalFull = #imageLiteral(resourceName: "ThreeRedOvalFull.png")
    let ThreeRedOvalEmpty = #imageLiteral(resourceName: "ThreeRedOvalEmpty.png")
    let ThreeRedOvalLined = #imageLiteral(resourceName: "ThreeRedOvalLined.png")
    let ThreeRedSFull = #imageLiteral(resourceName: "ThreeRedSFull.png")
    let ThreeRedSEmpty = #imageLiteral(resourceName: "ThreeRedSEmpty.png")
    let ThreeRedSLined = #imageLiteral(resourceName: "ThreeRedSLined.png")
    let ThreePurpleDiamondFull = #imageLiteral(resourceName: "ThreePurpleDiamondFull.png")
    let ThreePurpleDiamondEmpty = #imageLiteral(resourceName: "ThreePurpleDiamondEmpty.png")
    let ThreePurpleDiamondLined = #imageLiteral(resourceName: "ThreePurpleDiamondLined.png")
    let ThreePurpleOvalFull = #imageLiteral(resourceName: "ThreePurpleOvalFull.png")
    let ThreePurpleOvalEmpty = #imageLiteral(resourceName: "ThreePurpleOvalEmpty.png")
    let ThreePurpleOvalLined = #imageLiteral(resourceName: "ThreePurpleOvalLined.png")
    let ThreePurpleSFull = #imageLiteral(resourceName: "ThreePurpleSFull.png")
    let ThreePurpleSEmpty = #imageLiteral(resourceName: "ThreePurpleSEmpty.png")
    let ThreePurpleSLined = #imageLiteral(resourceName: "ThreePurpleSLined.png")
    var cards : [card]
    
    init() {
        cards = [card]()
        cards.append(card.init(pic: ThreePurpleSLined, color: "Purple", num: 3, shape: "S", fill: "lined"))
        cards.append(card.init(pic: ThreePurpleSEmpty, color: "Purple", num: 3, shape: "S", fill: "empty"))
        cards.append(card.init(pic: ThreePurpleSFull, color: "Purple", num: 3, shape: "S", fill: "full"))
        cards.append(card.init(pic: ThreePurpleOvalLined, color: "Purple", num: 3, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: ThreePurpleOvalEmpty, color: "Purple", num: 3, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: ThreePurpleOvalFull, color: "Purple", num: 3, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: ThreePurpleDiamondLined, color: "Purple", num: 3, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: ThreePurpleDiamondEmpty, color: "Purple", num: 3, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: ThreePurpleDiamondFull, color: "Purple", num: 3, shape: "Diamond", fill: "full"))
        
        cards.append(card.init(pic: ThreeRedSLined, color: "Red", num: 3, shape: "S", fill: "lined"))
        cards.append(card.init(pic: ThreeRedSEmpty, color: "Red", num: 3, shape: "S", fill: "empty"))
        cards.append(card.init(pic: ThreeRedSFull, color: "Red", num: 3, shape: "S", fill: "full"))
        cards.append(card.init(pic: ThreeRedOvalLined, color: "Red", num: 3, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: ThreeRedOvalEmpty, color: "Red", num: 3, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: ThreeRedOvalFull, color: "Red", num: 3, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: ThreeRedDiamondLined, color: "Red", num: 3, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: ThreeRedDiamondEmpty, color: "Red", num: 3, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: ThreeRedDiamondFull, color: "Red", num: 3, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: ThreeGreenSLined, color: "Green", num: 3, shape: "S", fill: "lined"))
        cards.append(card.init(pic: ThreeGreenSEmpty, color: "Green", num: 3, shape: "S", fill: "empty"))
        cards.append(card.init(pic: ThreeGreenSFull, color: "Green", num: 3, shape: "S", fill: "full"))
        cards.append(card.init(pic: ThreeGreenOvalLined, color: "Green", num: 3, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: ThreeGreenOvalEmpty, color: "Green", num: 3, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: ThreeGreenOvalFull, color: "Green", num: 3, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: ThreeGreenDiamondLined, color: "Green", num: 3, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: ThreeGreenDiamondEmpty, color: "Green", num: 3, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: ThreeGreenDiamondFull, color: "Green", num: 3, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: TwoPurpleSLined, color: "Purple", num: 2, shape: "S", fill: "lined"))
        cards.append(card.init(pic: TwoPurpleSEmpty, color: "Purple", num: 2, shape: "S", fill: "empty"))
        cards.append(card.init(pic: TwoPurpleSFull, color: "Purple", num: 2, shape: "S", fill: "full"))
        cards.append(card.init(pic: TwoPurpleOvalLined, color: "Purple", num: 2, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: TwoPurpleOvalEmpty, color: "Purple", num: 2, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: TwoPurpleOvalFull, color: "Purple", num: 2, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: TwoPurpleDiamondLined, color: "Purple", num: 2, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: TwoPurpleDiamondEmpty, color: "Purple", num: 2, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: TwoPurpleDiamondFull, color: "Purple", num: 2, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: TwoRedSLined, color: "Red", num: 2, shape: "S", fill: "lined"))
        cards.append(card.init(pic: TwoRedSEmpty, color: "Red", num: 2, shape: "S", fill: "empty"))
        cards.append(card.init(pic: TwoRedSFull, color: "Red", num: 2, shape: "S", fill: "full"))
        cards.append(card.init(pic: TwoRedOvalLined, color: "Red", num: 2, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: TwoRedOvalEmpty, color: "Red", num: 2, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: TwoRedOvalFull, color: "Red", num: 2, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: TwoRedDiamondLined, color: "Red", num: 2, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: TwoRedDiamondEmpty, color: "Red", num: 2, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: TwoRedDiamondFull, color: "Red", num: 2, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: TwoGreenSLined, color: "Green", num: 2, shape: "S", fill: "lined"))
        cards.append(card.init(pic: TwoGreenSEmpty, color: "Green", num: 2, shape: "S", fill: "empty"))
        cards.append(card.init(pic: TwoGreenSFull, color: "Green", num: 2, shape: "S", fill: "full"))
        cards.append(card.init(pic: TwoGreenOvalLined, color: "Green", num: 2, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: TwoGreenOvalEmpty, color: "Green", num: 2, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: TwoGreenOvalFull, color: "Green", num: 2, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: TwoGreenDiamondLined, color: "Green", num: 2, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: TwoGreenDiamondEmpty, color: "Green", num: 2, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: TwoGreenDiamondFull, color: "Green", num: 2, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: OnePurpleSLined, color: "Purple", num: 1, shape: "S", fill: "lined"))
        cards.append(card.init(pic: OnePurpleSEmpty, color: "Purple", num: 1, shape: "S", fill: "empty"))
        cards.append(card.init(pic: OnePurpleSFull, color: "Purple", num: 1, shape: "S", fill: "full"))
        cards.append(card.init(pic: OnePurpleOvalLined, color: "Purple", num: 1, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: OnePurpleOvalEmpty, color: "Purple", num: 1, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: OnePurpleOvalFull, color: "Purple", num: 1, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: OnePurpleDiamondLined, color: "Purple", num: 1, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: OnePurpleDiamondEmpty, color: "Purple", num: 1, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: OnePurpleDiamondFull, color: "Purple", num: 1, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: OneRedSLined, color: "Red", num: 1, shape: "S", fill: "lined"))
        cards.append(card.init(pic: OneRedSEmpty, color: "Red", num: 1, shape: "S", fill: "empty"))
        cards.append(card.init(pic: OneRedSFull, color: "Red", num: 1, shape: "S", fill: "full"))
        cards.append(card.init(pic: OneRedOvalLined, color: "Red", num: 1, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: OneRedOvalEmpty, color: "Red", num: 1, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: OneRedOvalFull, color: "Red", num: 1, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: OneRedDiamondLined, color: "Red", num: 1, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: OneRedDiamondEmpty, color: "Red", num: 1, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: OneRedDiamondFull, color: "Red", num: 1, shape: "Diamond", fill: "full"))

        cards.append(card.init(pic: OneGreenSLined, color: "Green", num: 1, shape: "S", fill: "lined"))
        cards.append(card.init(pic: OneGreenSEmpty, color: "Green", num: 1, shape: "S", fill: "empty"))
        cards.append(card.init(pic: OneGreenSFull, color: "Green", num: 1, shape: "S", fill: "full"))
        cards.append(card.init(pic: OneGreenOvalLined, color: "Green", num: 1, shape: "Oval", fill: "lined"))
        cards.append(card.init(pic: OneGreenOvalEmpty, color: "Green", num: 1, shape: "Oval", fill: "empty"))
        cards.append(card.init(pic: OneGreenOvalFull, color: "Green", num: 1, shape: "Oval", fill: "full"))
        cards.append(card.init(pic: OneGreenDiamondLined, color: "Green", num: 1, shape: "Diamond", fill: "lined"))
        cards.append(card.init(pic: OneGreenDiamondEmpty, color: "Green", num: 1, shape: "Diamond", fill: "empty"))
        cards.append(card.init(pic: OneGreenDiamondFull, color: "Green", num: 1, shape: "Diamond", fill: "full"))
        
    }
    
    
    
}
